<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

return ["stream_actions" => ["actions" => ["curl" => "CURL", "iframe" => "Open in iframe", "frame" => "Open in frameset (outdated)", "group" => "Send to campaign", "campaign" => "Send to campaign", "stream" => "Send to stream", "js" => "JS redirect", "http" => "HTTP redirect", "remote" => "REMOTE", "formsubmit" => "FormSubmit", "show_text" => "Show as text", "show_html" => "Show as HTML", "status404" => "404 NotFound", "meta" => "Meta redirect", "double_meta" => "Double meta redirect", "blank_referrer" => "Redirect without Referer", "do_nothing" => "Do nothing", "js_for_iframe" => "Redirect for iframe (Deprecated)", "js_for_script" => "Redirect for script (Deprecated)"], "action_descriptions" => ["curl" => "Help to load external page without actually redirecting", "frame" => "Show page in a frameset", "iframe" => "Show page in a iframe", "meta" => "Redirects by using 'meta' HTML tag", "js" => "Use JS to perform redirect", "double_meta" => "Two-step redirect that helps hide source from the destination website", "blank_referrer" => "Redirect that doesn't send Referer", "http" => "Recommended. Simple and the most reliable redirect", "remote" => "Two-step action: load the page content then use it as the next URL for redirecting", "formsubmit" => "The way to perform redirect with POST-data", "do_nothing" => "Just leave the user where he is now", "campaign" => "Send to another campaign (duplictes clicks for every campaign)", "status404" => "Show blank page with error '404 Not Found'", "show_html" => "Show HTML content", "show_text" => "Show plain text content", "js_for_iframe" => "Use \"JS redirect\" instead", "js_for_script" => "Use \"JS redirect\" instead"], "action_incompatible" => "This action is incompatible with current integration method. Please choose a more appropriate action in the stream.", "categories" => ["tooltip_landing" => "\n            If you want to upload your page, choose \"Local\".\n            To redirect to an external page, choose \"Redirect\".\n            If you want to load an external page but without performing redirect, choose \"Preloaded\".\n            ", "tooltip_offer" => "\n            If you want to upload your page, choose \"Local\".\n            To redirect to an external page, choose \"Redirect\".\n            If you want to load an external page but without performing redirect, choose \"Preloaded\".\n            ", "local" => "Local", "preloaded" => "Preload", "external" => "Redirect", "other" => "Other", "redirect" => "Redirect", "action" => "Action"]]];

?>