<?php
if (empty($title)) {
    throw new \Exception('no $title');
}
if (is_null($isProduction)) {
    throw new \Exception('no $isProduction');
}
if (empty($revision)) {
    throw new \Exception('no $revision');
}
if (empty($revision)) {
    throw new \Exception('no $revision');
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title><?php echo $title ?></title>
    <?php include 'shared/_head.phtml' ?>
    <?php
    if ($isProduction) {
        echo '<link href="assets/app.css?' . $revision . '" media="screen" rel="stylesheet" type="text/css" />';
    }
    ?>
</head>
<body class="error-system">
    <div class="container">
        <div class="row justify-content-center align-items-center error-system-row">
            <div class="col-lg-5">
                <div class="card error-system-card <?php echo (isset($alert)) ? $alert : '' ?>">
                    <div class="card-body">
                        <?php echo is_array($content) ? json_encode($content) : $content ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="application/javascript">var kData = {}; var kTranslations = {}</script>
    <?php include 'shared/_footer.phtml' ?>
</body>
</html>
