<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

namespace Component\Reports\Grid;

class ReportDefinition extends \Component\Clicks\Grid\ClicksDefinition
{
    protected $_url = "?object=reports.build";
    protected $_rangeIntervals = NULL;
    public function getTitle()
    {
        return \Core\Locale\LocaleService::t("reports.title");
    }
    public function initColumns()
    {
        self::initColumns();
        $this->addColumn(new \Component\Grid\Definition\Column("profitability", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "#", "sortable" => true, "groupable" => false, "category" => "money", "sort_by" => "profitability", "metric" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PROFITABILITY, "inner_select" => ["CASE \n                WHEN SUM(lead_revenue + sale_revenue - cost) > 0 THEN 1 \n                WHEN SUM(lead_revenue + sale_revenue - cost) < 0 THEN -1\n                ELSE 0 END" => "profitability"], "required_columns" => ["lead_revenue", "sale_revenue", "cost"], "group_by" => "profitability", "exclude_from_details" => true, "width" => 3, "resizable" => false, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("label", ["type" => \Component\Grid\Definition\Column::STRING, "title" => "#", "th_title" => "#", "metric" => true, "category" => "data", "hidden" => true, "virtual" => true, "template" => "LabelsCell", "resizable" => false, "width" => 62, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("year", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["DATE_FORMAT(CONVERT_TZ(`datetime`, '+00:00', @timezone), '%Y')" => "year"], "group_by" => "`year`", "category" => "calendar", "width" => 80]));
        $this->addColumn(new \Component\Grid\Definition\Column("month", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["DATE_FORMAT(CONVERT_TZ(`datetime`, '+00:00', @timezone), '%Y/%m')" => "month"], "group_by" => "`month`", "category" => "calendar", "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONTH, "width" => 80]));
        $this->addColumn(new \Component\Grid\Definition\Column("week", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["YEARWEEK(CONVERT_TZ(`datetime`, '+00:00', @timezone), 7)" => "week"], "group_by" => "`week`", "category" => "calendar", "formatter" => \Component\Grid\Definition\Column::FORMATTER_WEEK, "decorator" => \Component\Grid\Builder\Decorator::WEEK, "width" => 80]));
        $this->addColumn(new \Component\Grid\Definition\Column("weekday", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["WEEKDAY(CONVERT_TZ(`datetime`, '+00:00', @timezone))" => "weekday"], "group_by" => "weekday", "category" => "calendar", "formatter" => \Component\Grid\Definition\Column::FORMATTER_WEEKDAY, "width" => 80]));
        $this->addColumn(new \Component\Grid\Definition\Column("day", ["type" => \Component\Grid\Definition\Column::DATE, "sortable" => true, "groupable" => true, "inner_select" => ["DATE(CONVERT_TZ(`datetime`, '+00:00', @timezone))" => "day"], "group_by" => "`day`", "category" => "calendar", "width" => 90]));
        $this->addColumn(new \Component\Grid\Definition\Column("hour", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["DATE_FORMAT(CONVERT_TZ(`datetime`, '+00:00', @timezone), '%H')" => "hour"], "group_by" => "`hour`", "category" => "calendar", "formatter" => \Component\Grid\Definition\Column::FORMATTER_HOUR, "width" => 80]));
        $this->addColumn(new \Component\Grid\Definition\Column("day_hour", ["type" => \Component\Grid\Definition\Column::STRING, "sortable" => true, "groupable" => true, "inner_select" => ["DATE_FORMAT(CONVERT_TZ(`datetime`, '+00:00', @timezone), '%Y%m%d%H')" => "`day_hour`"], "group_by" => "`day_hour`", "category" => "calendar", "formatter" => \Component\Grid\Definition\Column::FORMATTER_DAY_HOUR, "width" => 90]));
        $this->addColumn(new \Component\Grid\Definition\Column("clicks", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["COUNT(click_id)" => "clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 52, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("campaign_unique_clicks", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.campaign_unique_clicks_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_unique_campaign)" => "campaign_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("stream_unique_clicks", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.stream_unique_clicks_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_unique_stream)" => "stream_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("global_unique_clicks", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.global_unique_clicks_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_unique_global)" => "global_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("uc_campaign_rate", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.uc_campaign_rate_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "summary" => true, "outer_select" => ["campaign_unique_clicks * 100.0 / clicks" => "uc_campaign_rate"], "required_columns" => ["clicks", "campaign_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("uc_stream_rate", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.uc_stream_rate_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "summary" => true, "outer_select" => ["stream_unique_clicks * 100.00 / clicks" => "uc_stream_rate"], "required_columns" => ["clicks", "stream_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("uc_global_rate", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.uc_global_rate_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "summary" => true, "outer_select" => ["global_unique_clicks * 100.00 /clicks " => "uc_global_rate"], "required_columns" => ["clicks", "global_unique_clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("bots", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "sortable" => true, "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_bot)" => "bots"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("bot_share", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "category" => "metrics", "summary" => true, "summary_average" => true, "inner_select" => ["SUM(is_bot) / COUNT(click_id) * 100" => "bot_share"], "required_columns" => ["bots", "clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("proxies", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "sortable" => true, "category" => "metrics", "inner_select" => ["SUM(is_using_proxy)" => "proxies"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("empty_referrers", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.empty_referrers_th", "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "sortable" => true, "category" => "metrics", "inner_select" => ["SUM(is_empty_referrer)" => "empty_referrers"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("conversions", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.conversions_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["(SUM(is_sale) + SUM(is_lead) + SUM(is_rejected))" => "conversions"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 50, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("leads", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_lead)" => "leads"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("sales", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_sale)" => "sales"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("rejected", ["type" => \Component\Grid\Definition\Column::INTEGER, "th_title" => "grid.rejected_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(is_rejected)" => "rejected"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("rebills", ["type" => \Component\Grid\Definition\Column::INTEGER, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "category" => "metrics", "summary" => true, "inner_select" => ["SUM(rebills)" => "rebills"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("approve", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "summary" => true, "outer_select" => ["(sales) * 100.00 / conversions" => "approve"], "required_columns" => ["sales", "leads", "conversions"], "decorator" => \Component\Grid\Builder\Decorator::DECIMAL, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("revenue", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "category" => "money", "inner_select" => ["SUM(lead_revenue) + SUM(sale_revenue)" => "revenue"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("lead_revenue", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "summary" => true, "category" => "money", "inner_select" => ["SUM(lead_revenue)" => "lead_revenue"], "fraction_size" => 4, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("sale_revenue", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.sale_revenue_th", "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "summary" => true, "inner_select" => ["SUM(sale_revenue)" => "sale_revenue"], "category" => "money", "fraction_size" => 4, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("rejected_revenue", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "inner_select" => ["SUM(rejected_revenue)" => "rejected_revenue"], "summary" => true, "category" => "money", "fraction_size" => 4, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("cost", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "summary" => true, "category" => "money", "inner_select" => ["SUM(cost)" => "cost"], "fraction_size" => 2, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "width" => 70, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("profit", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.profit_th", "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "category" => "money", "inner_select" => ["SUM(lead_revenue) + SUM(sale_revenue) - SUM(cost)" => "profit"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 2, "width" => 70, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("profit_confirmed", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.profit_confirmed_th", "metric" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "sortable" => true, "category" => "money", "inner_select" => ["SUM(sale_revenue) - SUM(cost)" => "profit_confirmed"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 2, "width" => 70, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("lp_clicks", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::INTEGER], "formatter" => \Component\Grid\Definition\Column::FORMATTER_INTEGER, "category" => "metrics", "summary" => true, "inner_select" => ["SUM(landing_clicked)" => "lp_clicks"], "width" => 80, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("lp_ctr", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "summary" => true, "outer_select" => ["lp_clicks * 100.00 / clicks" => "lp_ctr"], "required_columns" => ["lp_clicks", "clicks"], "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE_H, "fraction_size" => 2, "width" => 80, "axis" => "volume"]));
        $this->getColumn("landing_clicked_period")->set(["inner_select" => ["AVG(TIME_TO_SEC(TIMEDIFF(landing_clicked_datetime,datetime)))" => "landing_clicked_period"]]);
        $this->addColumn(new \Component\Grid\Definition\Column("cr", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.cr_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(leads + sales + rejected) * 100.00 / clicks" => "cr"], "required_columns" => ["leads", "sales", "rejected", "clicks"], "summary" => true, "decorator" => \Component\Grid\Builder\Decorator::DECIMAL, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 72, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("crs", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.crs_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["sales * 100.00 / clicks" => "crs"], "required_columns" => ["sales", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 72, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("crl", ["type" => \Component\Grid\Definition\Column::DECIMAL, "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["leads * 100.00 / clicks" => "crl"], "required_columns" => ["leads", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE, "fraction_size" => 2, "width" => 72, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("roi", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.roi_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(lead_revenue + sale_revenue - cost) * 100.00 / cost" => "roi"], "required_columns" => ["lead_revenue", "sale_revenue", "cost"], "summary" => true, "decorator" => \Component\Grid\Builder\Decorator::DECIMAL, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE_H, "fraction_size" => 2, "width" => 70, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("roi_confirmed", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.roi_confirmed_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(sale_revenue - cost) * 100.00 / cost" => "roi_confirmed"], "required_columns" => ["sale_revenue", "cost"], "summary" => true, "decorator" => \Component\Grid\Builder\Decorator::DECIMAL, "formatter" => \Component\Grid\Definition\Column::FORMATTER_PERCENTAGE_H, "fraction_size" => 2, "width" => 70, "axis" => "volume"]));
        $this->addColumn(new \Component\Grid\Definition\Column("epc", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.epc_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["((lead_revenue + sale_revenue) / clicks)" => "epc"], "required_columns" => ["lead_revenue", "sale_revenue", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 86, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("epc_confirmed", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.epc_confirmed_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["sale_revenue / clicks" => "epc_confirmed"], "required_columns" => ["sale_revenue", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("cps", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.cps_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["cost / (sales)" => "cps"], "required_columns" => ["cost", "sales"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("cpa", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.cpa_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["cost / conversions" => "cpa"], "required_columns" => ["cost", "conversions"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("cpc", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.cpc_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["cost / clicks" => "cpc"], "required_columns" => ["cost", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 70, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ecpc", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.ecpc_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["cost / clicks * 1000" => "ecpc"], "required_columns" => ["cost", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ecpm", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.ecpm_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(lead_revenue + sale_revenue - cost) * 1000 / clicks" => "ecpm"], "required_columns" => ["lead_revenue", "sale_revenue", "cost", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ecpm_confirmed", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.ecpm_confirmed_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(sale_revenue - cost) * 1000 / clicks" => "ecpm_confirmed"], "required_columns" => ["sale_revenue", "cost", "clicks"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ec", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.ec_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["(lead_revenue + sale_revenue) / (leads + sales + rebills + rejected)" => "ec"], "required_columns" => ["lead_revenue", "sale_revenue", "leads", "sales", "rebills", "rejected"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ec_confirmed", ["type" => \Component\Grid\Definition\Column::DECIMAL, "th_title" => "grid.ec_confirmed_th", "metric" => true, "sortable" => true, "filter" => ["type" => \Component\Grid\Definition\Column::DECIMAL], "category" => "metrics", "outer_select" => ["sale_revenue / (leads + sales + rebills + rejected)" => "ec_confirmed"], "required_columns" => ["sale_revenue", "leads", "sales", "rebills", "rejected"], "summary" => true, "formatter" => \Component\Grid\Definition\Column::FORMATTER_MONEY, "fraction_size" => 4, "width" => 80, "axis" => "money"]));
        $this->addColumn(new \Component\Grid\Definition\Column("ip_mask1", ["type" => \Component\Grid\Definition\Column::STRING, "relation" => "ref_ips", "inner_select" => ["SUBSTRING_INDEX(INET_NTOA(t_ref_ips.value),\".\",2)" => "ip_mask1"], "group_by" => "ip_mask1", "filter" => ["type" => \Component\Grid\Definition\Column::STRING], "decorator" => \Component\Grid\Builder\Decorator::MASK1, "groupable" => true, "sortable" => true, "category" => "ip", "width" => 115]));
        $this->addColumn(new \Component\Grid\Definition\Column("ip_mask2", ["type" => \Component\Grid\Definition\Column::STRING, "relation" => "ref_ips", "inner_select" => ["SUBSTRING_INDEX(INET_NTOA(t_ref_ips.value),\".\",3)" => "ip_mask2"], "group_by" => "ip_mask2", "filter" => ["type" => \Component\Grid\Definition\Column::STRING], "decorator" => \Component\Grid\Builder\Decorator::MASK2, "groupable" => true, "sortable" => true, "category" => "ip", "width" => 100]));
    }
}

?>