<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

return ["offers" => ["title" => "Offers", "offer" => "Offer", "help" => "http://v9.help.keitaro.io/en/offers", "choose" => "Choose Offer", "create" => "Create Offer", "add" => "Add Offers", "added" => "Offer added", "empty" => "No offers found", "name" => "Offer Name", "url" => "URL", "url_would_add" => "These params append to the URL: ", "creating" => "Create Offer", "editing" => "Edit Offer", "created" => "The offer has been created", "deleted" => "The offer has been deleted", "restored" => "The offer has been restored", "group" => "TableGroup", "affiliate_network" => "Affiliate Network", "payout_type" => "Payout Type", "payout_type_desc" => "If CPA is selected, revenue is set after receiving postback from affiliate network.\n           If CPC is selected, revenue is set immediately after sending visitor to offer.\n         С оплатой за клик, доход выставляется сразу после отправки пользователя на оффер.", "payout" => "Payout", "payout_desc" => "\n            If \"auto\" is enabled value of payout is got from parameter \"payout\" in postback (&payout=0.5&currency=usd).\n            In other case, parameter \"payout\" is ignored.\n            Option \"Upsell\" (rebills) allows to increase of revenue without increasing conversions count (leads, sales).\n            If the \"Upsell\" is enabled, it's necessary to send unique value in param \"tid\".\n            ", "select_affiliate_network" => "Select affiliate network", "please_choose_network" => "Enter name of affiliate network", "select" => "Select", "payout_auto" => "Auto", "payout_upsell" => "Upsells (rebills)", "cost_types" => ["CPC" => "CPC (Cost per Click)", "CPA" => "CPA (Cost per Action)"], "countries" => "Countries", "countries_desc" => "That list will be displayed near the offer name", "offer_type" => "Type", "no_tid" => "To make Upsells work, aff. network must send param 'tid' through postback URL.", "conversion_cap" => "Conversion Cap", "conversion_cap_desc" => "Enable that feature if the offer limit conversions per day", "daily_cap" => "Daily Cap", "daily_cap_desc" => "Daily limit of conversions, after which the tracker will send traffic to another offer", "timezone_desc" => "Which timezone is being used by the affiliate network for calculating conversions", "alternative_offer" => "Alternative Offer", "alternative_offer_desc" => "Where to send traffic when daily limit is reached", "no_alternative_offer" => "You must choose alternative offer"]];

?>